name: Manual Homebrew Release

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  release-homebrew:
    name: Trigger Homebrew Formula Update
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get latest tag
        id: latest
        run: |
          tag=$(gh release view --json tagName -q .tagName)
          echo "Latest release tag: $tag"
          echo "tag=$tag" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Send dispatch to homebrew-tap
        env:
          GH_TOKEN: ${{ secrets.REPO_DISPATCH_PAT }}
        run: |
          tag="${{ steps.latest.outputs.tag }}"
          repo="${{ github.event.repository.name }}"
          echo "Dispatching tag $tag from $repo"
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GH_TOKEN" \
            https://api.github.com/repos/chenasraf/homebrew-tap/dispatches \
            -d "{\"event_type\":\"trigger-from-release\",\"client_payload\":{\"tag\":\"$tag\",\"repo\":\"$repo\"}}"
