name: Release

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

permissions:
  contents: write
  pull-requests: write

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
      - name: Test
        run: go test -v ./...

  generate:
    name: Generate cross-platform builds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Create dist/ dir
        run: mkdir dist
      - name: Generate build files
        uses: chenasraf/go-cross-build@v1
        with:
          platforms: 'linux/amd64, darwin/amd64, windows/amd64, darwin/arm64'
          package: ''
          name: 'sofmani'
          compress: 'true'
          dest: 'dist'
      - name: Upload builds
        if: github.ref == 'refs/heads/master'
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  release-please:
    name: Release
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs:
      - test
      - generate
    steps:
      - uses: actions/checkout@v4
      - name: Download builds
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - name: Verify Release Artifacts
        run: |
          ls -la dist
          for i in "linux-amd64" "darwin-amd64" "windows-amd64" "darwin-arm64"; do
            if [[ ! -f ./dist/sofmani-$i.tar.gz ]]; then
              echo "File not found: ./dist/sofmani-$i.tar.gz"
              exit 1
            fi
          done
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: simple
      - name: Upload Release Artifacts
        if: ${{ steps.release.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ steps.release.outputs.tag_name }} ./dist/sofmani-linux-amd64.tar.gz
          gh release upload ${{ steps.release.outputs.tag_name }} ./dist/sofmani-darwin-amd64.tar.gz
          gh release upload ${{ steps.release.outputs.tag_name }} ./dist/sofmani-darwin-arm64.tar.gz
          gh release upload ${{ steps.release.outputs.tag_name }} ./dist/sofmani-windows-amd64.tar.gz
